name: Deploy

on:
  push:
    tags:      
      - v*

jobs:
  deploy_to_test:
    environment: test
    name: Deploy to Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: npm_package_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Print version
        run: echo "${{ steps.npm_package_version.outputs.version }}"

  deploy_to_production:
    environment: prod
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: npm_package_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Print version
        run: echo "${{ steps.npm_package_version.outputs.version }}"
